name: Build and test frontend app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Echo message
        run: echo "Building frontend app"
      - name: Build frontend app
        run: npm install && npm run build